### ISSUE TITLE
Add page for each event

### ISSUE THREAD

**Issue by dirv** [QueerCodeOrg/queercodeberlin.github.io#56]
It should describe when and where, who is speaking, and who is organizing.

**Comment by jonsanders101** [comment]
As a slight variation on this, would it be worth creating a page which lists kinds of events we run to give newcomers a sense of the range of activities we're about? E.g. talks, breakfast and catch-up, skills sessions, co-working, board game evenings. This information could be on the website all the time, regardless of whether there are any particular events planned in the near future, so that we're not relying on individual events pages being up and maintained for us to still look fun and busy.

**Comment by dirv** [comment]
Thanks @jonsanders101 - this is what #8, #6, #7 and #13 were intending to do. We can try to close those as part of this issue.
